In [1]:
import pandas as pd
df = pd.read_csv('Day_10_banking_data.csv')
filtered_by_transaction_amount = df[df['Transaction_Amount'] <= 2000]
print("Rows where Transaction_Amount is <= 2000:")
print(filtered_by_transaction_amount)
loan_payment_high_balance = df[(df['Transaction_Type'] == 'Loan Payment') & (df['Account_Balance'] > 5000)]
print("\nRows with 'Loan Payment' and Account_Balance > 5000:")
print(loan_payment_high_balance)
uptown_branch_transactions = df[df['Branch'] == 'Uptown']
print("\nTransactions made in the 'Uptown' branch:")
print(uptown_branch_transactions)

Rows where Transaction_Amount is <= 2000:
          Date       Account_Type    Branch Transaction_Type  \
0   2023-01-19      Fixed Deposit   Central     Loan Payment
1   2023-01-16            Current    Uptown       Withdrawal
3   2023-01-18            Savings    Uptown     Loan Payment
6   2023-01-04  Recurring Deposit   Central   Service Charge
9   2023-01-11      Fixed Deposit  Downtown          Deposit
10  2023-01-13  Recurring Deposit   Central          Deposit
11  2023-01-08      Fixed Deposit  Suburban   Service Charge
12  2023-01-15      Fixed Deposit    Uptown   Service Charge
18  2023-01-12  Recurring Deposit  Suburban   Service Charge

    Transaction_Amount  Account_Balance
0               985.51          6839.59
1               641.43          8908.39
3              1914.60          5776.63
6              1621.82          6465.79
9              1529.59          2592.16
10              846.41          6443.14
11             1803.88          6560.58
12             1225.50          4224.47
18             1339.57          8666.74

Rows with 'Loan Payment' and Account_Balance > 5000:
          Date       Account_Type   Branch Transaction_Type  \
0   2023-01-19      Fixed Deposit  Central     Loan Payment
2   2023-01-10            Current   Uptown     Loan Payment
3   2023-01-18            Savings   Uptown     Loan Payment
7   2023-01-09            Current  Central     Loan Payment
13  2023-01-05  Recurring Deposit  Central     Loan Payment
17  2023-01-07            Current  Central     Loan Payment

    Transaction_Amount  Account_Balance
0               985.51          6839.59
2              3363.85         12428.67
3              1914.60          5776.63
7              2346.72         10708.85
13             4683.64          6762.43
17             4116.52          9785.64

Transactions made in the 'Uptown' branch:
          Date   Account_Type  Branch Transaction_Type  Transaction_Amount  \
1   2023-01-16        Current  Uptown       Withdrawal              641.43
2   2023-01-10        Current  Uptown     Loan Payment             3363.85
3   2023-01-18        Savings  Uptown     Loan Payment             1914.60
12  2023-01-15  Fixed Deposit  Uptown   Service Charge             1225.50

    Account_Balance
1           8908.39
2          12428.67
3           5776.63
12          4224.47

In [2]:
df['Transaction_Fee'] = df['Transaction_Amount'] * 0.02
print("\nData with the new 'Transaction_Fee' column:")
print(df[['Transaction_Amount', 'Transaction_Fee']])s
df['Balance_Status'] = df['Account_Balance'].apply(lambda x: 'High Balance' if x > 5000 else 'Low Balance')
print("\nData with the new 'Balance_Status' column:")
print(df[['Account_Balance', 'Balance_Status']])

Data with the new 'Transaction_Fee' column:
    Transaction_Amount  Transaction_Fee
0               985.51          19.7102
1               641.43          12.8286
2              3363.85          67.2770
3              1914.60          38.2920
4              2788.57          55.7714
5              4584.05          91.6810
6              1621.82          32.4364
7              2346.72          46.9344
8              3899.98          77.9996
9              1529.59          30.5918
10              846.41          16.9282
11             1803.88          36.0776
12             1225.50          24.5100
13             4683.64          93.6728
14             4136.54          82.7308
15             3350.32          67.0064
16             4421.57          88.4314
17             4116.52          82.3304
18             1339.57          26.7914
19             4516.52          90.3304

Data with the new 'Balance_Status' column:
    Account_Balance Balance_Status
0           6839.59   High Balance
1           8908.39   High Balance
2          12428.67   High Balance
3           5776.63   High Balance
4           4779.04    Low Balance
5           7635.47   High Balance
6           6465.79   High Balance
7          10708.85   High Balance
8          12646.56   High Balance
9           2592.16    Low Balance
10          6443.14   High Balance
11          6560.58   High Balance
12          4224.47    Low Balance
13          6762.43   High Balance
14          8175.08   High Balance
15         12836.51   High Balance
16          8330.40   High Balance
17          9785.64   High Balance
18          8666.74   High Balance
19          8789.19   High Balance